services:
  wlcs.api:
    image: ${DOCKER_REGISTRY-}wlcsapi
    container_name: wlcs.api
    build:
      context: .
      dockerfile: src/API/WLCS.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 

  wlcs.gateway:
    image: ${DOCKER_REGISTRY-}wlcsgateway
    container_name: wlcs.gateway
    build:
      context: .
      dockerfile: src/API/WLCS.Gateway/Dockerfile
    ports:
      - 3000:8080
      - 3001:8081

  wlcs.database:
    image: postgres:latest
    container_name: wlcs.database
    environment:
      - POSTGRES_DB=wlcs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wlcs.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: wlcs.identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080

  wlcs.seq:
    image: datalust/seq:latest
    container_name: wlcs.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  wlcs.redis:
    image: redis:latest
    container_name: wlcs.redis
    restart: always
    ports:
      - 6379:6379
  
  wlcs.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: wlcs.jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  wlcs.mongo:
    image: mongo:latest
    container_name: wlcs.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.containers/mongo:/data/db
    ports:
      - 27017:27017

  wlcs.queue:
    image: rabbitmq:management-alpine
    container_name: wlcs.queue
    hostname: wlcs-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672


