version: '3.4'

services:
  wlcs.api:
    image: ${DOCKER_REGISTRY-}wlcsapi
    container_name: WLCS.Api
    build:
      context: .
      dockerfile: src/api/WLCS.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
  
  wlcs.database:
    image: postgres:latest
    container_name: WLCS.Database
    environment:
      POSTGRES_USER: wlcs
      POSTGRES_PASSWORD: wlcs
      POSTGRES_DB: wlcs
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wlcs.seq:
    image: datalust/seq:latest
    container_name: WLCS.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
