// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WLCS.Modules.Competitions.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Platforms : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "platforms",
                schema: "competitions",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    meet_id = table.Column<Guid>(type: "uuid", nullable: false),
                    platform_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_platforms", x => x.id);
                    table.ForeignKey(
                        name: "fk_platforms_meets_meet_id",
                        column: x => x.meet_id,
                        principalSchema: "competitions",
                        principalTable: "meets",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "competition_platform",
                schema: "competitions",
                columns: table => new
                {
                    competitions_id = table.Column<Guid>(type: "uuid", nullable: false),
                    platform_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_competition_platform", x => new { x.competitions_id, x.platform_id });
                    table.ForeignKey(
                        name: "fk_competition_platform_competitions_competitions_id",
                        column: x => x.competitions_id,
                        principalSchema: "competitions",
                        principalTable: "competitions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_competition_platform_platforms_platform_id",
                        column: x => x.platform_id,
                        principalSchema: "competitions",
                        principalTable: "platforms",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_competition_platform_platform_id",
                schema: "competitions",
                table: "competition_platform",
                column: "platform_id");

            migrationBuilder.CreateIndex(
                name: "ix_platforms_meet_id",
                schema: "competitions",
                table: "platforms",
                column: "meet_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "competition_platform",
                schema: "competitions");

            migrationBuilder.DropTable(
                name: "platforms",
                schema: "competitions");
        }
    }
}
