// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace WLCS.Modules.Administration.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Create_Database : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "administration");

            migrationBuilder.CreateTable(
                name: "permissions",
                schema: "administration",
                columns: table => new
                {
                    code = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_permissions", x => x.code);
                });

            migrationBuilder.CreateTable(
                name: "roles",
                schema: "administration",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_roles", x => x.name);
                });

            migrationBuilder.CreateTable(
                name: "users",
                schema: "administration",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    first_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    last_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    identity_id = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_users", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "role_permissions",
                schema: "administration",
                columns: table => new
                {
                    permission_code = table.Column<string>(type: "character varying(50)", nullable: false),
                    role_name = table.Column<string>(type: "character varying(50)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_role_permissions", x => new { x.permission_code, x.role_name });
                    table.ForeignKey(
                        name: "fk_role_permissions_permissions_permission_code",
                        column: x => x.permission_code,
                        principalSchema: "administration",
                        principalTable: "permissions",
                        principalColumn: "code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_role_permissions_roles_role_name",
                        column: x => x.role_name,
                        principalSchema: "administration",
                        principalTable: "roles",
                        principalColumn: "name",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "user_roles",
                schema: "administration",
                columns: table => new
                {
                    roles_name = table.Column<string>(type: "character varying(50)", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user_roles", x => new { x.roles_name, x.user_id });
                    table.ForeignKey(
                        name: "fk_user_roles_roles_roles_name",
                        column: x => x.roles_name,
                        principalSchema: "administration",
                        principalTable: "roles",
                        principalColumn: "name",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_user_roles_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "administration",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "administration",
                table: "permissions",
                column: "code",
                values: new object[]
                {
                    "athletes:create",
                    "athletes:read",
                    "athletes:search",
                    "athletes:update",
                    "competitions:create",
                    "competitions:read",
                    "competitions:update",
                    "meets:create",
                    "meets:read",
                    "meets:search",
                    "meets:update",
                    "users:read",
                    "users:update"
                });

            migrationBuilder.InsertData(
                schema: "administration",
                table: "roles",
                column: "name",
                values: new object[]
                {
                    "Administrator",
                    "CompDirector",
                    "User"
                });

            migrationBuilder.InsertData(
                schema: "administration",
                table: "role_permissions",
                columns: new[] { "permission_code", "role_name" },
                values: new object[,]
                {
                    { "athletes:create", "Administrator" },
                    { "athletes:create", "CompDirector" },
                    { "athletes:read", "Administrator" },
                    { "athletes:search", "Administrator" },
                    { "athletes:search", "CompDirector" },
                    { "athletes:search", "User" },
                    { "athletes:update", "Administrator" },
                    { "athletes:update", "CompDirector" },
                    { "competitions:create", "Administrator" },
                    { "competitions:create", "CompDirector" },
                    { "competitions:update", "Administrator" },
                    { "competitions:update", "CompDirector" },
                    { "meets:create", "Administrator" },
                    { "meets:create", "CompDirector" },
                    { "meets:read", "Administrator" },
                    { "meets:search", "Administrator" },
                    { "meets:search", "CompDirector" },
                    { "meets:search", "User" },
                    { "meets:update", "Administrator" },
                    { "meets:update", "CompDirector" },
                    { "users:read", "Administrator" },
                    { "users:update", "Administrator" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_role_permissions_role_name",
                schema: "administration",
                table: "role_permissions",
                column: "role_name");

            migrationBuilder.CreateIndex(
                name: "ix_user_roles_user_id",
                schema: "administration",
                table: "user_roles",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_users_email",
                schema: "administration",
                table: "users",
                column: "email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_users_identity_id",
                schema: "administration",
                table: "users",
                column: "identity_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "role_permissions",
                schema: "administration");

            migrationBuilder.DropTable(
                name: "user_roles",
                schema: "administration");

            migrationBuilder.DropTable(
                name: "permissions",
                schema: "administration");

            migrationBuilder.DropTable(
                name: "roles",
                schema: "administration");

            migrationBuilder.DropTable(
                name: "users",
                schema: "administration");
        }
    }
}
