# Login

POST http://localhost:18080/realms/wlcs/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=wlcs-public-client&scope=email openid&username=hmsiegel@test.com&password=password

###

# Refresh

POST http://localhost:18080/realms/wlcs/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=wlcs-public-client&refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4MzE2NTIxYS00YmI3LTQ3NjItYWNiMS01YzhkZTMwMjQ5OGIifQ.eyJleHAiOjE3MTkwMjE0MTcsImlhdCI6MTcxOTAxOTYxNywianRpIjoiMWRmOThiNzgtZWMwYi00YTBkLWJhNzktYmRjNTBmMjE4ZjIwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvd2xjcyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTgwODAvcmVhbG1zL3dsY3MiLCJzdWIiOiI5YTIzZDcxNi1mMDU5LTQyMTAtYWY5Mi1mOTZhN2M5NjljMWMiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoid2xjcy1wdWJsaWMtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImZhM2Y4Mjg2LWRhMDAtNGFmNS04YzliLWY5MGY3MjhlNDExOSIsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJmYTNmODI4Ni1kYTAwLTRhZjUtOGM5Yi1mOTBmNzI4ZTQxMTkifQ.N11jexTbjaUTu4EM5cwY7Q19FNf2-njNY6I3ULI_y1h2fklhAGwByPMXc1qmzoXxGx7po_xaCexcjmU-6HToeg
