POST {{Host}}/competitions/meet
Content-Type: application/json

{
    "name": "2024 Ohio WSO Championship",
    "location": "Columbus, OH",
    "venue": "Greater Columbus Convention Center",
    "startdate": "2024-08-31",
    "enddate": "2024-09-01"
}
