POST {{Host}}/competitions/meets
Content-Type: application/json

{
    "name": "2024 American Open Series 1",
    "location": "Columbus, OH",
    "venue": "Greater Columbus Convention Center",
    "startdate": "2024-02-29",
    "enddate": "2024-03-03"
}
