// <copyright file="ResultT.cs" company="WLCS">
// Copyright (c) WLCS. All rights reserved.
// </copyright>

namespace WLCS.Common.Domain;

/// <summary>
/// Represents a result with a type.
/// </summary>
/// <typeparam name="TValue">The type of teh result.</typeparam>
#pragma warning disable SA1649 // File name should match first type name
public class Result<TValue> : Result
#pragma warning restore SA1649 // File name should match first type name
{
  private readonly TValue? _value;

  /// <summary>
  /// Initializes a new instance of the <see cref="Result{TValue}"/> class.
  /// </summary>
  /// <param name="value">The value of the result.</param>
  /// <param name="isSuccess">Indicates if the result was a success.</param>
  /// <param name="error">The error generated by the result.</param>
  public Result(TValue? value, bool isSuccess, Error error)
      : base(isSuccess, error)
  {
    _value = value;
  }

  /// <summary>
  /// Gets the value of the result.
  /// </summary>
  [NotNull]
  public TValue Value => IsSuccess
      ? _value!
      : throw new InvalidOperationException("The value of a failure result can't be accessed.");

  /// <summary>
  /// Represents an empty success result.
  /// </summary>
  /// <param name="value">The value of the result.</param>
#pragma warning disable CA2225 // Operator overloads have named alternates
  public static implicit operator Result<TValue>(TValue? value) =>
      value is not null ? Success(value) : Failure<TValue>(Error.NullValue);
#pragma warning restore CA2225 // Operator overloads have named alternates

  /// <summary>
  /// Represents a validation failure result.
  /// </summary>
  /// <param name="error">The error generated by the result.</param>
  /// <returns>The result.</returns>
#pragma warning disable CA1000 // Do not declare static members on generic types
  public static Result<TValue> ValidationFailure(Error error) =>
      new(default, false, error);
#pragma warning restore CA1000 // Do not declare static members on generic types
}
